# Generated by Django 4.2.6 on 2023-10-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_conteorapidopunto_nombreagente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescatepunto',
            name='embarazo',
            field=models.BooleanField(default=False),
        ),
    ]
